### ISSUE TITLE
[New Cohort] Linear Algebra - Foundations to Frontiers Rohit NMIMS

### ISSUE THREAD

**Issue by ropats16** [ossu/cohorts#32]
## Class

Data Science / Linear Algebra / Linear Algebra - Foundations to Frontiers

## Coordinators (1/3)

- Rohit Pathare
- Dharmesh Patel

## Students (1/20)

- @dp0397

## Start Date

_Choose a start date for your cohort. We suggest providing two weeks for other students to join._

**Comment by dp0397** [comment]
plis add lord patty

**Comment by amorriscode** [comment]
@ropats16 when do you plan to start this cohort?

**Comment by dmytronayda** [comment]
When do you please plan to start?

**Comment by alnav** [comment]
Hello, I'm interested in joining the group, let me know when you start

**Comment by ropats16** [comment]
> @ropats16 when do you plan to start this cohort?

I do not know how to operate the cohort. Can someone help ?

**Comment by amorriscode** [comment]
@ropats16 there really isn't a set way to communicate. We usually recommend you create a channel for communication. [Our main chat is on Gitter](https://gitter.im/open-source-society/computer-science), so that could be a good option.

Other than that you just need to set a start date and go for it. The cohort should be self-organizing and it's up to the coordinators and the students to decide what works best.
