### ISSUE TITLE
[New Cohort] How to Code - Complex Data

### ISSUE THREAD

**Issue by compscilimited** [ossu/cohorts#38]
## Class

Computer Science / Core Programming / How to Code - Complex Data

## Students (1/20)

_We suggest a minimum of 5 students per cohort, with no more than 20_.

- compscilimited

## Start Date

19th July 2019

**Comment by Trebbau** [comment]
Is there anybody out there? Pls let me know! I need some help with the making of schedules! 
Thanks

**Comment by amorriscode** [comment]
@Trebbau I'm closing this cohort as it is quite old/inactive. Feel free to make a new one.

**Comment by Trebbau** [comment]
Hi Anthony, just one question. Were you able to solve the scheduling assignment? I'm having difficulty solving this one. I know I need to blend aspects of backtracking over an arbitrary arity tree that is generatively produced and recursed over. There is also two one-of types in the arguments so that I can analyze the inputs through a matrix of all the cases as simplify thus. I just can't seem to put all together in the right way. Can you help me out with this? I would be willing to pay if you can help me successfully finish this one.  Can I send over my code?

Thanks in advance,

Carlos 

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 23, 2020, 10:35 by notifications@github.com:

**Comment by amorriscode** [comment]
@Trebbau sorry I can't help here! I didn't complete the course, I'm just managing cohorts. Perhaps you could ask in the [Gitter channel](https://gitter.im/open-source-society/computer-science)?

**Comment by Trebbau** [comment]
Thanks for the tip!
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 23, 2020, 14:40 by notifications@github.com:

**Comment by Trebbau** [comment]
Just out of curiosity: what is ossu? Someone on gitter channel opened up a room with that acronym on how to code - complex data. Can you enlighten me?
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 23, 2020, 14:40 by notifications@github.com:

**Comment by amorriscode** [comment]
@Trebbau the [OSSU is a path to a free, self-taught education in Computer Science](https://github.com/ossu/computer-science)! It's on GitHub and maintained by a community of passionate folks.

**Comment by Trebbau** [comment]
Sounds exciting friend! I'll check it out, thanks.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 24, 2020, 08:21 by notifications@github.com:
