### ISSUE TITLE
Future of Cohorts

### ISSUE THREAD

**Issue by amorriscode** [ossu/cohorts#43]
Hi everyone! 👋 

I have been neglecting the cohorts lately but have been wondering how we could make them better. 

One of the biggest problems is a platform for communication. Various channels have been used for comms (Slack, Telegram, Discord, etc.). Our official communication tool is [Gitter](https://github.com/ossu/cohorts/issues/43).

What do you think we could do to make cohorts more accessible and successful?

**Comment by waciumawanjohi** [comment]
I wonder if it would be useful to have a regular social hour where everyone gathers on a video chat and just says hello. This could increase the awareness of others in the program. And there could simply be a regular announcement at the beginning/end of the meeting that students are encouraged to form cohorts.

One tweak that could make things more manageable interaction wise: create 1 video feed chat where everyone is muted and then have a separate app for voice chat. The voice chat can have multiple different rooms. This can simulate an actual in person mix and mingle, where you can see everybody, but each conversation is a manageable size. My work team uses a similar setup using Zoom and Teamspeak. I've heard that Sococo does this natively, but I've never used it myself.

**Comment by teddiconfetti** [comment]
Like the idea! I vote zoom or google hangouts as the least faily of hangout kind of software.

**Comment by daniel65dj** [comment]
Teams can be also considered. I think we are less than 200 or whatever the free limit was.

**Comment by waciumawanjohi** [comment]
My impression has been that its rare for a cohort to be proposed. My hypothesis is that it's generally an intimidating process to put yourself out there without knowing if there are any other learners interested in the same class at the same time as you. Having a regular social get together would increase the connection between students, lowering the barriers to recruiting each other for cohorts.

Is my impression (that cohorts are rarely proposed) correct? Or is there a larger problem that needs addressing?

**Comment by parthpatel227** [comment]
I think we can take a look at how CS50x manages their discord channel. Instead of many different cohorts on the same topic we can encourage creating one for each course. That way there will be a sort of flexibility to the learning process as help can be sought out for a specific topic. Also to keep the use of cohort that is to take the course together, we can have waves of the course as required. To elaborate every month or every two month there can be a new wave in the same discord/Gitter channel to encourage learning together, all the while the topics channels being open for asking questions and communicating. Now this approach may differ from course to course based on number of participants but it may be a good start because even if you can't regularly participate in the communication, you have a single source of interaction for the course and you can join the wave(cohort) whenever you want a more rigorous approach. Sorry if my English isn't up to the mark, its not my first language.

**Comment by amorriscode** [comment]
@waciumawanjohi you're mostly correct, cohorts do not happen to frequently but the idea would be that they do.

I think this had made me think a lot more about the _community_ behind OSSU. How could we strengthen it?

I love what @parthpatel227 suggested where we just have a chat group where we have channels for each course. Instead of doing cohorts, each course could have a living channel where current and previous students can gather to discuss things.

For me, I think we would benefit from using a different chat platform to allow for these types of communications. Building the community more might be valuable. From my perspective it seems like all the focus has been on the curriculum (which is obviously very important) but less on optimizing the community itself.

**Comment by waciumawanjohi** [comment]
@amorriscode I hear you when you say that there's been more attention on the curriculum than on the community. I've definitely filed far more issues about comparing different classes than I have about different community strategies. Glad to dig into this aspect of OSSU. It's important!

I hope that as we proceed we can use something like design thinking. I would hate to start with a solution (e.g. let's institute a social hour) without having figured out the problem.

I've heard you point out some technical issues of Gitter: "we cannot create rooms under the umbrella OSSU". Can you sharpen that; why is that a problem? If students can create OSSU-April-2020-HTDP in gitter, why is OSSU concerned that it's not under the umbrella?

I think that OSSU has some problems around community:
* Students and contributors have little visibility on what others are doing in the curriculum.
* Students are sparse. That is, for any individual course, there are never more than a handful of students pursuing it at the same time. This limits the ability of students to collaborate.
* OSSU has created presences on a number of platforms only to abandon them. Example, I was under the impression that the reddit page had been taken down. But there have been people posting there in 2020, receiving no answer because no one in OSSU monitors it any more. This cycle of new platform->abandoned platform has limited continuity and likely caused churn in the community.

I hope that we can: 
1. Choose a problem
2. Generate a number of options for solving the problem and discuss their benefits and risks
3. Choose a solution and run a small experiment to test our hypothesis.

**Comment by amorriscode** [comment]
@waciumawanjohi great summaries of the problems. I wholeheartedly agree. I like the idea of doing some design thinking.

I'll elaborate a little bit on why Gitter isn't a great solution.

I mentioned that it isn't easy to link cohort chats or channels to the broader OSSU. The reason this is important and should be considered by the OSSU, is because it doesn't actually generate community. 

Like you mentioned, there aren't that many students in one cohort at a time. A lot of people don't finish, either. If everyone from every cohort could collaborate in a channel (say on Slack/Discord) then we would immediately be bringing people together. We could also be linking to other things related to a) that class or b) OSSU without having to direct them to other places.

If we are to do bigger things, like bringing people together for virtual meetups, I think it would be useful to have an "Events" channel. If you wanted to follow events, you could. How could we do that currently? Posting an event in Gitter would be lost quite quickly.

I agree with you about the abandonment of various platforms. It's unfortunate that it has happened. I think that's a side effect of trying to be on **every** platform, instead of **one** platform.

If I were to propose a single problem, I would state it as this:

The OSSU community is currently divided. How do we bring the OSSU together, as a community, so everyone can support each other and grow together?

**Comment by waciumawanjohi** [comment]
This makes sense. And from what you've written, the subproblem we're trying to address is something like, "When a cohort creates some medium for communication, if students get out of sync they are not likely to remain engaged with either the cohort or the broader OSSU community."

You've mentioned Slack and Discord. I've also been pondering Sococo.

Are there other brainstorm ideas?

**Comment by robbrit** [comment]
Chiming in here with some thoughts.

I absolutely like the idea of a social hour - it helps put faces to names into the community that aren't just lines in a chatroom. Also if you go into a video chat and see a real person in there, you know immediately that if you ask a question it will get answered. A chatroom doesn't always have the same appeal.
I'd be willing to volunteer for an hour-long session every week - I'd use Hangouts myself since it's free, doesn't require any installation, and you can share the session with just a simple link.

Back to the topic of cohorts and channels: I am not convinced that a channel per course would be beneficial - the current chatroom is not overwhelming with activity, and I think splitting up into smaller channels would subtract from the sense of community rather than add to it.

Some sort of organization/leadership around cohorts is important to connect people - someone saying "I am running this cohort" so that people have a place to turn to. There will occasionally be students who will do this, but based on the past turnout they will be few and far between. Instead the idea of a TA who leads the course would work well - they don't need to be a student or watch the videos and do all the assignments, instead they are the go-to-person for anyone interested in taking the course. Again I'd volunteer to lead 1-2 courses simultaneously to try this format out.

Some more advertising for cohorts would also help: posting in the chatroom a few times about cohorts starting, announcing it in the social hour, etc. The most important part of the advertisement would be to point to the person leading the cohort and telling people to get in touch.

**Comment by aryzach** [comment]
While this is a little off topic of cohorts, it's still community centered. I think some sort of alumni / experienced OSSU student network would be really useful. In my case, I started learning CS on my own, and was / still am the only one studying for this. I'd be nice to be able to reach out to somebody even if they've just taken a few more classes than me and compare notes on our experience with OSSU, where they are now, what they would've done differently, etc. It also might be a good 'next steps' network whether that's job related or applying to graduate programs. 

Additionally, I think a city-based OSSU network would be really cool. Studying alone is isolating, and it would be really cool to meet up with another OSSU-er, even if it's just for lunch once.

I'd also volunteer to help 'TA' a cohort if that becomes a thing.

**Comment by mguidoti** [comment]
Hello everyone, 

I'm kind of a new guy here. I attempted to get involved in a cohort in the past, but couldn't keep it up at that time (overwhelmed with work, finishing PhD and a Udacity nanodegree, settling in my country, etc). Now I'm planning to get really on - and I'm following this important discussion (community is everything) so I decided to share my two cents, based on my experiences.

Although I might not have been so active in my original cohort, I remember that we tried to organized a cohort-specific communication channel on Telegram, and it wasn't really useful/cool/handy because of the app, not because of the idea of having a place were you can discuss and exchange with people that are more or less at the same point as you in the curriculum. 

I'm also a UoPeople student, and we used to have a very interesting Slack community with course-specific channels. As it was pointed out already, these were often inactive. However, the fact that former students used to stick around for a little while was very helpful, and I do remember seeing people getting help when needed. Inactive but not ineficient. In this community we never had facetime, which I think it's a great idea to connect people, and it could be organized on the general channel or even on the cohort-specific channels. 

I guess what I'm trying to say is that, from my experience, both course-specific and cohort-specific channels under the OSSU umbrella seems to be a very interesting and effective strategy to tackle the problem outlined here. Even that some might be less active than the others, these different type of channels play different roles and all of them contributes to the sense of community that is under discussion here. Slack seems to be the best available option, as Sococo is fairly pricy, right?

**Comment by Alaharon123** [comment]
Discord has a significantly better feature-set for free users than slack

**Comment by xxylem** [comment]
Hi all,

I agree that a regular (weekly/fortnightly?) social hour would be great. 

### 1. Gitter

I also would like to echo others' comments about Gitter. I struggle to follow what is happening on that app; there is no sense of threads/channels: all conversations are mixed in one spot. I get an email once per day that says I have 100+ unread messages, and without any ability to filter for what might interest me (e.g. by channel), I am not motivated to scroll through that.

[I only just realised that there are more chat rooms on the Gitter related to other curriculums](https://gitter.im/open-source-society/home). I had to click a globe icon in the top right (why would I click this? I only did it now because I am exploring). So, it seems possible to have multiple channels on Gitter, but at the moment, they are very coarse grained (one per curriculum). Unfortunately, that site does not signpost well that the "room" is part of a "community" (compare to, e.g. Discord, where all channels on the server are listed clearly down the left hand side). [**Perhaps we should link to the "community" page instead and have many more rooms?**](https://gitter.im/open-source-society/home)

**Also, I just noticed that if you click the link 'open-source-society/computer-science' at the top of the Gitter page, [it leads to a 404](https://github.com/open-source-society).**

### 2. Cohorts

Regarding the accessibility of Cohorts, I wasn't aware of its existence until @waciumawanjohi pointed it out to me the other week. I typically just immediately go to the section of the curriculum I am on when I need to refer back to the page, so I must have missed its addition. How could we reach out to people about this cohort opportunity? **Maybe we could have news updates/messages in the Gitter or something similar to announce upcoming cohorts?** **Or what about links in the course tables to the relevant cohort page (if it exists)?**

I think another (related) issue to consider is that students (beginners) who are new to Git, Github and this sort of site may find it difficult to navigate (I know when I was starting I mostly just stuck to the readme page). How can we increase discoverability of the the Cohort repo? **[Could we move it up on the repos list](https://github.com/ossu)? What about if we add a friendly description to the repo (remembering that a new student may not even know what a repo is)?** 

Maybe some pictures on the curriculum would help? It's hard to explain what a Gitter/Cohort/etc is in words, and then convince someone they should click the link, but a picture of a chat window is immediately obvious.

**Comment by pcolt** [comment]
I consider my self a OSSU's student from the end of 2019. 
Following the idea of the design thinking approach from my point of view the problem that I see regarding OSSU's community is that is missing a unique and strong tool able to create a community of students.
At the moment the Git Hub page is working very well to maintain and collaborate to the Curriculum but it is not doing so well in terms of community of students enrolled with all the needs that a student have. 
In my case my very first need would be to see and contact other students that are following like me the OSSU Curriculum. It would be also useful to be able to contact some sort of expert or tutor considering the possibility that that students may be also tutors. How can be easily done this I don't know, but in my opinion what is needed could be:
1. a sort of profile for every student (we could choose some platform and stick with it?)
2. a place collecting a list of students following the curriculum (that could be made in the same platform as above?)
3. a place to collect public discussion regarding single courses and/or topics
4. a tool to chat directly with other students?

Resuming my idea: Git Hub is very good to collaborate maintaining and building the Curriculum, but it is not so good at creating a community of students. So it may be a good idea to look for a better platform to do the latter. What do you think? May I missing something about Git Hub and some ways to build such student community and list inside Git Hub? 

Hope this helps! And sorry for my poor English which is not my first language  :-)

**Comment by spamegg1** [comment]
Most people who ever come across OSSU will have a lazer sharp focus on the curriculum and nothing else. I never knew Gitter, Cohorts, or even Extras existed until recently.

Also people will not read the "prose" inside README. They will just scroll down to the list of courses. Then some of them will come to Gitter and ask questions that are already answered in the "prose".

Therefore: on the curriculum, right next to each course, we must have links directly to a current cohort taking that class and its Gitter/whatever chat room. Kinda like this:

Courses | Duration | Effort | Prerequisites | Students currently taking this class | 
:-- | :--: | :--: | :--:
[How to Code - Simple Data](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x) | 7 weeks | 8-10 hours/week | none | [Chat with your cohorts](https://gitter.im/open-source-society/computer-science/HtCSD)

**Comment by waciumawanjohi** [comment]
This issue generated a good amount of discussion which spanned 3 months. Having seen no new comments in 1.5 months, I believe it is time to close the issue and take action.

**Findings**:
- Students and mentors are dissatisfied with Gitter as a communication channel. In particular, the inability to create channels associated with the main discussion channels splinters communication.
- There is wide support for creating course specific discussion channels.
- There is more support for using discord over slack.
- There is support for some regularly scheduled social hour.
- There is concern about discoverability of discussion channels and support for linking each channel next to the course in the CS repo.
- There are mentors who are interested in leading cohorts who would like to have cohort specific channels.

**Outcome**
I have created a discord server for OSSU. This server has a channel for each curriculum. There is a category for cohort specific channels. We will need to create a process for students leading cohorts to be able to create and later retire these channels.
Next steps:
1. To all the contributors who have commented on this issues, please [join the discord](https://discord.gg/5pUhfpX)! Drop in a message to let new students know that they are joining a wonderful learning community.
https://discord.gg/5pUhfpX
2. I've created [a pull request on the computer science curriculum](https://github.com/ossu/computer-science/pull/771). This switches the link to gitter with a link to the discord server. It also incorporates the excellent suggestion of putting a link for each course's discussion channel next to the course listing. I will merge this pull request in at the end of the weekend.
3. At the end of the weekend I will also post in Gitter letting students know that they should migrate to the Discord server.
